### ISSUE TITLE
Probeer zo veel mogelijk CSS en JS te scheiden 

### ISSUE THREAD

**Issue by Knetters** [Robin1224/fix-the-flow-ui-events-2023#1]
https://github.com/Robin1224/fix-the-flow-ui-events-2023/blob/a0d90a1a777522e52499cd851d39e5990228edfd/src/app.js#L174

Hier is het misschien verstandig om je CSS en je JS te scheiden van elkaar. Ookal is dit meer werk is het wel netter.

**Comment by Robin1224** [comment]
<img src="https://github.com/Robin1224/fix-the-flow-ui-events-2023/assets/81151231/eac3a272-97b9-46d3-8354-42a616dcdfdc" align="left" width="250px" />

Thankyou voor de feedback :)

Ik ben het met je eens dat JS en CSS apart moeten blijven, echter is er in dit geval een reden voor.

Tijdens het maken van deze deeltaak merkte ik dat het enorm hielp met debuggen om het aanmaken van de event listeners te loggen in de console, maar dit bleek heel onoverzichtelijk te zijn. Daarom had ik deze functie aangemaakt om styling toe te passen op de console logs, zodat ik ze makkelijker kon lezen. 

Styling in console.log() werkt via CSS properties, en dit is dus de reden dat er CSS in mijn javascript staat. Helaas is er (voor zover ik weet) geen andere manier om dit voor elkaar te krijgen.

_Meer info:_
https://developer.chrome.com/docs/devtools/console/format-style
